package com.test;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 8;
  public static final int ELSE = 15;
  public static final int PLUS = 3;
  public static final int RBRACE = 12;
  public static final int RPAREN = 10;
  public static final int WHILE = 21;
  public static final int SEMI = 2;
  public static final int RETURN = 22;
  public static final int GREATER = 18;
  public static final int IF = 14;
  public static final int LPAREN = 9;
  public static final int LBRACE = 11;
  public static final int ID = 24;
  public static final int TYPE = 25;
  public static final int EQUALS = 7;
  public static final int COMMA = 13;
  public static final int EEQUALS = 16;
  public static final int NUMBER = 23;
  public static final int LEQUALS = 19;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int LESSER = 20;
  public static final int GEQUALS = 17;
  public static final int BOOLCONST = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "EQUALS",
  "MOD",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "IF",
  "ELSE",
  "EEQUALS",
  "GEQUALS",
  "GREATER",
  "LEQUALS",
  "LESSER",
  "WHILE",
  "RETURN",
  "NUMBER",
  "ID",
  "TYPE",
  "BOOLCONST"
  };
}

